# Generated by Django 4.2.5 on 2023-10-20 21:44

from django.db import migrations, models
import django.db.models.deletion
import investing.models.newssentiment
import investing.models.securitymaster


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('relevance_score', models.DecimalField(decimal_places=4, max_digits=5, validators=[investing.models.newssentiment.validate_relevance_score_0_1])),
            ],
        ),
        migrations.AlterField(
            model_name='securitymaster',
            name='my_id',
            field=models.CharField(max_length=10, unique=True, validators=[investing.models.securitymaster.SecurityMaster.validate_my_id]),
        ),
        migrations.CreateModel(
            name='TickerSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('relevance_score', models.DecimalField(decimal_places=4, max_digits=5, validators=[investing.models.newssentiment.validate_relevance_score_0_1])),
                ('ticker_sentiment_score', models.DecimalField(decimal_places=6, max_digits=7)),
                ('ticker_sentiment_label', models.CharField(choices=[('Bearish', 'Bearish'), ('Somewhat-Bearish', 'Somewhat-Bearish'), ('Neutral', 'Neutral'), ('Somewhat-Bullish', 'Somewhat-Bullish'), ('Bullish', 'Bullish')], max_length=20)),
                ('security_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investing.securitymaster')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('time_published', models.DateTimeField()),
                ('authors', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=200)),
                ('source', models.CharField(max_length=50)),
                ('category_within_source', models.CharField(max_length=50)),
                ('overall_sentiment_score', models.DecimalField(decimal_places=6, max_digits=7)),
                ('overall_sentiment_label', models.CharField(choices=[('Bearish', 'Bearish'), ('Somewhat-Bearish', 'Somewhat-Bearish'), ('Neutral', 'Neutral'), ('Somewhat-Bullish', 'Somewhat-Bullish'), ('Bullish', 'Bullish')], max_length=20)),
                ('tickers', models.ManyToManyField(to='investing.tickersentiment')),
                ('topics', models.ManyToManyField(to='investing.topicsentiment')),
            ],
        ),
    ]
