# Generated by Django 4.2.5 on 2023-10-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0002_topicsentiment_alter_securitymaster_my_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicsentiment',
            name='topic',
            field=models.CharField(choices=[('blockchain', 'blockchain'), ('earnings', 'earnings'), ('ipo', 'ipo'), ('mergers_and_acquisitions', 'mergers_and_acquisitions'), ('financial_markets', 'financial_markets'), ('economy_fiscal', 'economy_fiscal'), ('economy_monetary', 'economy_monetary'), ('economy_macro', 'economy_macro'), ('energy_transportation', 'energy_transportation'), ('finance', 'finance'), ('life_sciences', 'life_sciences'), ('manufacturing', 'manufacturing'), ('real_estate', 'real_estate'), ('retail_wholesale', 'retail_wholesale'), ('technology', 'technology')], max_length=30),
        ),
    ]
