# Generated by Django 4.2.5 on 2023-10-23 17:52

from django.db import migrations, models
import investing.models.newssentiment


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0003_alter_topicsentiment_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newssentiment',
            old_name='tickers',
            new_name='ticker_sentiments',
        ),
        migrations.AlterField(
            model_name='securitymaster',
            name='asset_class',
            field=models.CharField(choices=[('BOND', 'BOND'), ('CRYPTO', 'CRYPTO'), ('EQUITY', 'EQUITY'), ('FX', 'FX'), ('NOT_SET', 'NOT_SET'), ('OPTION', 'OPTION')], max_length=20),
        ),
        migrations.AlterField(
            model_name='securitymaster',
            name='asset_subclass',
            field=models.CharField(choices=[('COMMON_STOCK', 'COMMON_STOCK'), ('CORP_BOND', 'CORP_BOND'), ('CRYPTO', 'CRYPTO'), ('EQUITY_OPTION', 'EQUITY_OPTION'), ('ETF', 'ETF'), ('FX', 'FX'), ('GOV_BOND', 'GOV_BOND'), ('INDEX_OPTION', 'INDEX_OPTION'), ('MUNI_BOND', 'MUNI_BOND'), ('NOT_SET', 'NOT_SET')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tickersentiment',
            name='relevance_score',
            field=models.DecimalField(decimal_places=6, max_digits=7, validators=[investing.models.newssentiment.validate_relevance_score_0_1]),
        ),
        migrations.AlterField(
            model_name='topicsentiment',
            name='relevance_score',
            field=models.DecimalField(decimal_places=6, max_digits=7, validators=[investing.models.newssentiment.validate_relevance_score_0_1]),
        ),
        migrations.AlterField(
            model_name='topicsentiment',
            name='topic',
            field=models.CharField(choices=[('blockchain', 'Blockchain'), ('earnings', 'Earnings'), ('economy_fiscal', 'Economy - Fiscal'), ('economy_macro', 'Economy - Macro'), ('economy_monetary', 'Economy - Monetary'), ('energy_transportation', 'Energy & Transportation'), ('finance', 'Finance'), ('financial_markets', 'Financial Markets'), ('ipo', 'IPO'), ('life_sciences', 'Life Sciences'), ('manufacturing', 'Manufacturing'), ('mergers_and_acquisitions', 'Mergers & Acquisitions'), ('real_estate', 'Real Estate & Construction'), ('retail_wholesale', 'Retail & Wholesale'), ('technology', 'Technology')], max_length=30),
        ),
    ]
