# Generated by Django 4.2.5 on 2023-10-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0005_investmentaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentaccount',
            options={'ordering': ['broker', 'account_name']},
        ),
        migrations.AddConstraint(
            model_name='investmentaccount',
            constraint=models.UniqueConstraint(fields=('broker', 'account_id'), name='unique_investing_investmentaccount_broker_accountid'),
        ),
    ]
