# Generated by Django 4.2.5 on 2023-10-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0010_alter_securitymaster_my_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentaccount',
            name='taxable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
