# Generated by Django 4.2.5 on 2023-10-26 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0012_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='close_date',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
            preserve_default=False,
        ),
    ]
