# Generated by Django 4.2.5 on 2023-10-27 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0015_alter_position_cost_basis_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='purchase_date',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securitymaster',
            name='asset_class',
            field=models.CharField(choices=[('BOND', 'BOND'), ('CRYPTO', 'CRYPTO'), ('EQUITY', 'EQUITY'), ('FX', 'FX'), ('MUTUAL_FUND', 'MUTUAL_FUND'), ('NOT_SET', 'NOT_SET'), ('OPTION', 'OPTION')], max_length=20),
        ),
        migrations.AlterField(
            model_name='securitymaster',
            name='asset_subclass',
            field=models.CharField(choices=[('COMMON_STOCK', 'COMMON_STOCK'), ('CORP_BOND', 'CORP_BOND'), ('CRYPTO', 'CRYPTO'), ('EQUITY_OPTION', 'EQUITY_OPTION'), ('ETF', 'ETF'), ('FX', 'FX'), ('GOV_BOND', 'GOV_BOND'), ('INDEX_OPTION', 'INDEX_OPTION'), ('MONEY_MARKET', 'MONEY_MARKET'), ('MUNI_BOND', 'MUNI_BOND'), ('NOT_SET', 'NOT_SET')], max_length=20),
        ),
    ]
