# Generated by Django 4.2.5 on 2023-10-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0016_position_purchase_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='cost_basis_avg',
            new_name='cost_basis_price',
        ),
    ]
