# Generated by Django 4.2.5 on 2023-10-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0017_rename_cost_basis_avg_position_cost_basis_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitymaster',
            name='has_fidelity_lots',
            field=models.BooleanField(default=True),
        ),
    ]
