# Generated by Django 4.2.5 on 2023-10-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0019_alter_position_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Required if broker breaks position into lots.', null=True),
        ),
    ]
