# Generated by Django 4.2.5 on 2023-10-29 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0020_alter_position_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField()),
                ('trans_type', models.CharField(choices=[('CORP_ACT', 'CORPORATE ACTION'), ('INTEREST', 'INTEREST'), ('OTHER', 'OTHER'), ('TRADE', 'TRADE'), ('TRANSFER', 'TRANSFER')], max_length=10)),
                ('action_type', models.CharField(choices=[('BUY', 'Buy'), ('BUY_COVER', 'Buy Cover'), ('CONVERSION', 'Conversion'), ('COUP_PMT', 'Coupon Payment'), ('DIVIDEND', 'Dividend'), ('INT_PMT', 'Interest Payment'), ('MERGER', 'Merger'), ('OPT_EXER', 'Option Exercise'), ('OPT_EXP', 'Option Expire'), ('SELL', 'Sell'), ('SELL_SHORT', 'Sell Short'), ('SPINOFF', 'Spin-Off'), ('STOCK_CONS', 'Stock Consolidation'), ('STOCK_DIV', 'Stock Dividend'), ('STOCK_SPLIT', 'Stock Split'), ('TRANSFER', 'Transfer')], max_length=11)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=6)),
                ('investment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investing.investmentaccount')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='investing.securitymaster')),
            ],
        ),
    ]
