# Generated by Django 4.2.5 on 2023-10-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0021_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='purchase_date',
            new_name='enter_date',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='close_date',
            new_name='eod_date',
        ),
    ]
