# Generated by Django 4.2.5 on 2023-10-30 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0022_rename_purchase_date_position_enter_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitymaster',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitymaster',
            name='option_type',
            field=models.CharField(blank=True, choices=[('AMERICAN_CALL', 'AMERICAN_CALL'), ('AMERICAN_PUT', 'AMERICAN_PUT'), ('EUROPEAN_CALL', 'EUROPEAN_CALL'), ('EUROPEAN_PUT', 'EUROPEAN_PUT')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='securitymaster',
            name='strike_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='securitymaster',
            name='underlying_security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='investing.securitymaster'),
        ),
        migrations.AlterField(
            model_name='securitymaster',
            name='asset_class',
            field=models.CharField(choices=[('BOND', 'BOND'), ('CRYPTO', 'CRYPTO'), ('EQUITY', 'EQUITY'), ('INDEX', 'INDEX'), ('FX', 'FX'), ('MUTUAL_FUND', 'MUTUAL_FUND'), ('NOT_SET', 'NOT_SET'), ('OPTION', 'OPTION')], max_length=20),
        ),
        migrations.AlterField(
            model_name='securitymaster',
            name='asset_subclass',
            field=models.CharField(choices=[('COMMON_STOCK', 'COMMON_STOCK'), ('CORP_BOND', 'CORP_BOND'), ('CRYPTO', 'CRYPTO'), ('EQUITY_OPTION', 'EQUITY_OPTION'), ('ETF', 'ETF'), ('FX', 'FX'), ('GOV_BOND', 'GOV_BOND'), ('INDEX', 'INDEX'), ('INDEX_OPTION', 'INDEX_OPTION'), ('MONEY_MARKET', 'MONEY_MARKET'), ('MUNI_BOND', 'MUNI_BOND'), ('NOT_SET', 'NOT_SET')], max_length=20),
        ),
    ]
