# Generated by Django 4.2.5 on 2023-10-31 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0023_securitymaster_expiration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateField()),
                ('close_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cost_basis_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_basis_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proceeds_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('proceeds_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('short_term_pnl', models.DecimalField(decimal_places=2, max_digits=12)),
                ('long_term_pnl', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_basis_price_unadj', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_basis_total_unadj', models.DecimalField(decimal_places=2, max_digits=12)),
                ('short_term_pnl_unadj', models.DecimalField(decimal_places=2, max_digits=12)),
                ('long_term_pnl_unadj', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investing.investmentaccount')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investing.securitymaster')),
            ],
        ),
    ]
