# Generated by Django 4.2.5 on 2023-10-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0024_closedposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedposition',
            name='cost_basis_price',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='cost_basis_price_unadj',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='cost_basis_total',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='cost_basis_total_unadj',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='long_term_pnl',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='long_term_pnl_unadj',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='proceeds_price',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='proceeds_total',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='short_term_pnl',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='short_term_pnl_unadj',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
    ]
