# Generated by Django 4.2.5 on 2023-11-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0026_investmentaccount_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedposition',
            name='cost_basis_price',
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='cost_basis_price_unadj',
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
        migrations.AlterField(
            model_name='closedposition',
            name='proceeds_price',
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
        migrations.AlterField(
            model_name='position',
            name='close_price',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='position',
            name='cost_basis_price',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
