# Generated by Django 4.2.5 on 2023-11-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0027_alter_closedposition_cost_basis_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='enter_price',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='enter_total',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitymaster',
            name='contract_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentaccount',
            name='create_date',
            field=models.DateField(help_text='Be wary of changing this to a more recent date (will cause issues with data including transactions, positions and others.'),
        ),
        migrations.AlterField(
            model_name='position',
            name='cost_basis_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='cost_basis_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
