# Generated by Django 4.2.5 on 2023-11-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0028_position_enter_price_position_enter_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='enter_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
