# Generated by Django 4.2.5 on 2023-11-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0029_alter_position_enter_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedposition',
            name='close_price',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedposition',
            name='enter_price',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
