# Generated by Django 4.2.5 on 2023-11-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0030_closedposition_close_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closedposition',
            old_name='close_price',
            new_name='close_price_net',
        ),
        migrations.RenameField(
            model_name='closedposition',
            old_name='enter_price',
            new_name='enter_price_net',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='close_price',
            new_name='eod_price',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='amount_net',
        ),
        migrations.AddField(
            model_name='position',
            name='enter_price_net',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='enter_total_net',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
