# Generated by Django 4.2.5 on 2023-11-11 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0031_rename_close_price_closedposition_close_price_net_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('BUY_COVER', 'Buy Cover'), ('CONVERSION', 'Conversion'), ('COUP_PMT', 'Coupon Payment'), ('DIVIDEND', 'Dividend'), ('INT_PMT', 'Interest Payment'), ('LOAN', 'Loan'), ('MERGER', 'Merger'), ('OPT_EXER', 'Option Exercise'), ('OPT_EXP', 'Option Expire'), ('SELL', 'Sell'), ('SELL_SHORT', 'Sell Short'), ('SPINOFF', 'Spin-Off'), ('STOCK_CONS', 'Stock Consolidation'), ('STOCK_DIV', 'Stock Dividend'), ('STOCK_SPLIT', 'Stock Split'), ('TRANSFER', 'Transfer')], max_length=11),
        ),
        migrations.CreateModel(
            name='TickerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_ticker', models.CharField(max_length=30)),
                ('old_ticker', models.CharField(max_length=30)),
                ('change_date', models.DateField()),
                ('change_type', models.CharField(choices=[('MERGER', 'Merger')], max_length=11)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investing.securitymaster')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tickerhistory',
            constraint=models.UniqueConstraint(fields=('security', 'change_date', 'change_type'), name='unique_investing_tickerhistory_sm_cd_ct'),
        ),
    ]
