# Generated by Django 4.2.5 on 2023-09-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depreciationbilldata',
            options={'ordering': ['real_estate', 'start_date', 'end_date', 'real_property_value']},
        ),
        migrations.AlterModelOptions(
            name='electricbilldata',
            options={'ordering': ['real_estate', 'start_date', '-is_actual']},
        ),
        migrations.AlterModelOptions(
            name='electricdata',
            options={'ordering': ['real_estate', 'year_month']},
        ),
        migrations.AlterModelOptions(
            name='estimatenote',
            options={'ordering': ['real_estate', 'service_provider', 'note_order']},
        ),
        migrations.AlterModelOptions(
            name='mortgagebilldata',
            options={'ordering': ['real_estate', 'start_date']},
        ),
        migrations.AlterModelOptions(
            name='mysunpowerhourlydata',
            options={'ordering': ['dt']},
        ),
        migrations.AlterModelOptions(
            name='natgasbilldata',
            options={'ordering': ['real_estate', 'start_date', '-is_actual']},
        ),
        migrations.AlterModelOptions(
            name='natgasdata',
            options={'ordering': ['real_estate', 'year_month']},
        ),
        migrations.AlterModelOptions(
            name='realestate',
            options={'ordering': ['address']},
        ),
        migrations.AlterModelOptions(
            name='realpropertyvalue',
            options={'ordering': ['real_estate', 'item']},
        ),
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'ordering': ['provider']},
        ),
        migrations.AlterModelOptions(
            name='simplebilldata',
            options={'ordering': ['real_estate', 'start_date', 'end_date']},
        ),
        migrations.AlterModelOptions(
            name='solarbilldata',
            options={'ordering': ['real_estate', 'start_date']},
        ),
        migrations.RemoveConstraint(
            model_name='electricdata',
            name='unique_realestate_electricdata_re_my',
        ),
        migrations.RemoveConstraint(
            model_name='natgasdata',
            name='unique_realestate_natgasdata_re_my',
        ),
        migrations.RenameField(
            model_name='electricdata',
            old_name='month_year',
            new_name='year_month',
        ),
        migrations.RenameField(
            model_name='natgasdata',
            old_name='month_year',
            new_name='year_month',
        ),
    ]
