# Generated by Django 4.2.5 on 2023-09-19 22:06

from django.db import migrations, models
import django.db.models.deletion
import realestate.models.depreciationbilldata
import realestate.models.electricbilldata
import realestate.models.electricdata
import realestate.models.estimatenote
import realestate.models.mortgagebilldata
import realestate.models.natgasbilldata
import realestate.models.natgasdata
import realestate.models.simplebilldata
import realestate.models.solarbilldata


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_alter_depreciationbilldata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciationbilldata',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to=realestate.models.depreciationbilldata.DepreciationBillData.file_upload_path),
        ),
        migrations.AddField(
            model_name='electricbilldata',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to=realestate.models.electricbilldata.ElectricBillData.file_upload_path),
        ),
        migrations.AddField(
            model_name='mortgagebilldata',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to=realestate.models.mortgagebilldata.MortgageBillData.file_upload_path),
        ),
        migrations.AddField(
            model_name='natgasbilldata',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to=realestate.models.natgasbilldata.NatGasBillData.file_upload_path),
        ),
        migrations.AddField(
            model_name='simplebilldata',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to=realestate.models.simplebilldata.SimpleBillData.file_upload_path),
        ),
        migrations.AddField(
            model_name='solarbilldata',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to=realestate.models.solarbilldata.SolarBillData.file_upload_path),
        ),
        migrations.AlterField(
            model_name='depreciationbilldata',
            name='service_provider',
            field=models.ForeignKey(limit_choices_to=realestate.models.depreciationbilldata.DepreciationBillData.valid_service_providers, on_delete=django.db.models.deletion.PROTECT, to='realestate.serviceprovider', validators=[realestate.models.depreciationbilldata.DepreciationBillData.validate_service_provider]),
        ),
        migrations.AlterField(
            model_name='electricbilldata',
            name='service_provider',
            field=models.ForeignKey(limit_choices_to=realestate.models.electricbilldata.ElectricBillData.valid_service_providers, on_delete=django.db.models.deletion.PROTECT, to='realestate.serviceprovider', validators=[realestate.models.electricbilldata.ElectricBillData.validate_service_provider]),
        ),
        migrations.AlterField(
            model_name='electricdata',
            name='service_provider',
            field=models.ForeignKey(limit_choices_to=realestate.models.electricdata.ElectricData.valid_service_providers, on_delete=django.db.models.deletion.PROTECT, to='realestate.serviceprovider', validators=[realestate.models.electricdata.ElectricData.validate_service_provider]),
        ),
        migrations.AlterField(
            model_name='estimatenote',
            name='service_provider',
            field=models.ForeignKey(limit_choices_to=realestate.models.estimatenote.EstimateNote.valid_service_providers, on_delete=django.db.models.deletion.PROTECT, to='realestate.serviceprovider', validators=[realestate.models.estimatenote.EstimateNote.validate_service_provider]),
        ),
        migrations.AlterField(
            model_name='mortgagebilldata',
            name='service_provider',
            field=models.ForeignKey(limit_choices_to=realestate.models.mortgagebilldata.MortgageBillData.valid_service_providers, on_delete=django.db.models.deletion.PROTECT, to='realestate.serviceprovider', validators=[realestate.models.mortgagebilldata.MortgageBillData.validate_service_provider]),
        ),
        migrations.AlterField(
            model_name='natgasbilldata',
            name='service_provider',
            field=models.ForeignKey(limit_choices_to=realestate.models.natgasbilldata.NatGasBillData.valid_service_providers, on_delete=django.db.models.deletion.PROTECT, to='realestate.serviceprovider', validators=[realestate.models.natgasbilldata.NatGasBillData.validate_service_provider]),
        ),
        migrations.AlterField(
            model_name='natgasdata',
            name='service_provider',
            field=models.ForeignKey(limit_choices_to=realestate.models.natgasdata.NatGasData.valid_service_providers, on_delete=django.db.models.deletion.PROTECT, to='realestate.serviceprovider', validators=[realestate.models.natgasdata.NatGasData.validate_service_provider]),
        ),
        migrations.AlterField(
            model_name='simplebilldata',
            name='service_provider',
            field=models.ForeignKey(limit_choices_to=realestate.models.simplebilldata.SimpleBillData.valid_service_providers, on_delete=django.db.models.deletion.PROTECT, to='realestate.serviceprovider', validators=[realestate.models.simplebilldata.SimpleBillData.validate_service_provider]),
        ),
        migrations.AlterField(
            model_name='solarbilldata',
            name='service_provider',
            field=models.ForeignKey(limit_choices_to=realestate.models.solarbilldata.SolarBillData.valid_service_providers, on_delete=django.db.models.deletion.PROTECT, to='realestate.serviceprovider', validators=[realestate.models.solarbilldata.SolarBillData.validate_service_provider]),
        ),
    ]
