# Generated by Django 4.2.5 on 2023-09-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_depreciationbilldata_bill_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricbilldata',
            name='bs_rate',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
